<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
* --------------------------------------------------------------------------------------------------
*
* Controller forms
* 
* List of forms
*
* Generated by application module maker.
*
* @since 	23/07/2014
* @author 	leandro.w3c@gmail.com
*
* --------------------------------------------------------------------------------------------------
*/
class forms extends ACME_Module_Controller {
	// Class attributes
	
	/**
	* __construct()
	*/
	public function __construct()
	{
		parent::__construct(__CLASS__);
	}
	
	/**
	* index()
	* Controller default method. Show a html table list with results 
	* of sql_list of module.
	* @return void
	*/
	public function index()
	{
		parent::index();
	}
	
	/**
	* example()
	* Example method of this controller. When an URL like forms/example 
	* will be called, this method is triggered.
	* @return void
	*/
	public function example()
	{
		$this->validate_permission('EXAMPLE');

		$this->template->load_page('controller_name/script', $array_of_arguments);
	}
}
