<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
* --------------------------------------------------------------------------------------------------
*
* Model <CLASS_NAME>_Model // Generated by application module maker
* 
* <DESCRIPTION>
*
* @since 	<CREATION_DATE>
* @author 	<AUTHOR>
*
* --------------------------------------------------------------------------------------------------
*/
class <CLASS_NAME>_Model extends CI_Model {
	
	/**
	* __construct()
	* Class constructor.
	*/
	public function __construct()
	{
		parent::__construct();
	}
	
	/**
	* example()
	* Model example method. When some controller invoke by the call 
	* $this-><CLASS_NAME>_Model->example(), this method will be triggered.
	* @return void
	*/
	public function example()
	{
		// How to manipulate queries
		/*
		$sql = "SELECT * FROM table";
		$data = $this->db->query($sql)->result_array();
		*/
	}
}
