<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
* --------------------------------------------------------------------------------------------------
*
* Controller <CLASS_NAME> // Generated by application module maker
* 
* <DESCRIPTION>
*
* @since 	<CREATION_DATE>
* @author 	<AUTHOR>
*
* --------------------------------------------------------------------------------------------------
*/
class <CLASS_NAME> extends ACME_Module_Controller {
	
	/**
	* __construct()
	* Class constructor.
	*/
	public function __construct()
	{
		parent::__construct(__CLASS__);
	}
	
	/**
	* index()
	* Controller default method. Show a html table list with results 
	* of sql_list from module.
	* @return void
	*/
	public function index()
	{
		parent::index();
	}
	
	/**
	* example()
	* Example method of this controller. When an URL like <CLASS_NAME>/example 
	* will be called, this method will be triggered.
	* @return void
	*/
	public function example()
	{
		$this->validate_permission('EXAMPLE');

		$this->template->load_page('controller_name/script', $array_of_arguments);
	}
}
